### ISSUE TITLE
Brainstorm

### ISSUE THREAD

**Issue by Hjordten** [Hjordten/GithubActions#1]

**Comment by YmerA38** [comment]
sikre at der bliver updatet, før der bliver pushet til main

**Comment by jonathanFS14** [comment]
deploy kode

**Comment by jonathanFS14** [comment]
automatisere simple kommandoer

**Comment by Hjordten** [comment]
## formål
- forstå syntaxen før vi koder
- Bruge det til at gøre det nemmere at styre sine versions/branches
- Bruge det til at sikre et godt workflow
- Version control.
- Sikrer at man ikke kan manipulere koden på branches på uønskede formål.
- Automatisering af simple opgaver. (f.eks. tjekke at man ikke pusher, før man har pullet).
- Teste at ens actions gør det forventede.
